name: ibmc_flutter_app_template
version: 0.0.1-dev.0
description: a Flutter template project for development by IBMC.
publish_to: none

dependencies:
  elementary: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.19.6

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/