name: ibmc_flutter_app_template
version: 0.0.1-dev.0
description: a Flutter template project for development by IBMC.
publish_to: none

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.4
  dio: ^5.4.3+1
  elementary: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  nested: ^1.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  spider: ^4.2.2

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.19.6

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/